### PR TITLE
setup: Github/workflows actions & Rubocop linters check

### LINKED ISSUE #24: [1pt] Set-up linters check

### PR DESCRIPTION
**Pull request by DanSam5K**
- Successfully set rubocop linters checkers

### CODE REVIEW

**Comment by aristides1000** [comment]
Good Job

**Review by aristides1000 — COMMENTED** [review]
Good job, you can merge the branch

**Review by enionsouza — APPROVED** [review]
Great job, @DanSam5K!
You can go ahead and merge this branch.

**Review by aristides1000 — APPROVED** [review]
Good job, you can merge this branch

**Pull request merged**
